
// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Cheburashka.Tests.BaselinedRuleTest.#ctor(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext,System.String,Microsoft.SqlServer.Dac.Model.TSqlModelOptions,Microsoft.SqlServer.Dac.Model.SqlServerVersion)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Cheburashka.Tests.BaselinedRuleTest.GetScriptsFolder(System.String)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Cheburashka.Tests.RuleTestUtils.SaveStringToFile(System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Cheburashka.Tests.RuleTest.CreateScriptedModel~Microsoft.SqlServer.Dac.Model.TSqlModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Cheburashka.Tests.RuleTest.CreateCodeAnalysisService(System.String)~Microsoft.SqlServer.Dac.CodeAnalysis.CodeAnalysisService")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Cheburashka.Tests.RuleTest.RunTest(System.String,System.Action{Microsoft.SqlServer.Dac.CodeAnalysis.CodeAnalysisResult,System.String})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Cheburashka.Tests.RuleTest.BuildDacpacFromModel(Microsoft.SqlServer.Dac.Model.TSqlModel)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Cheburashka.Tests.BaselinedRuleTest.RunVerification(Microsoft.SqlServer.Dac.CodeAnalysis.CodeAnalysisResult,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Cheburashka.Tests.RuleTest.RunRulesAndVerifyResult(Microsoft.SqlServer.Dac.CodeAnalysis.CodeAnalysisService,System.Action{Microsoft.SqlServer.Dac.CodeAnalysis.CodeAnalysisResult,System.String})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0105:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Cheburashka.Tests.RuleTest.AssertModelValid(Microsoft.SqlServer.Dac.Model.TSqlModel)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0105:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Cheburashka.Tests.RuleTest.DumpErrors(System.Collections.Generic.IList{Microsoft.SqlServer.Dac.Extensibility.ExtensibilityError})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Cheburashka.Tests.RuleTest.CreateDacpacModel(Microsoft.SqlServer.Dac.Model.TSqlModel)~Microsoft.SqlServer.Dac.Model.TSqlModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0105:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Cheburashka.Tests.RuleTest.ProblemComparer.Compare(Microsoft.SqlServer.Dac.CodeAnalysis.SqlRuleProblem,Microsoft.SqlServer.Dac.CodeAnalysis.SqlRuleProblem)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Cheburashka.Tests.RuleTest.DumpProblemsToString(System.Collections.Generic.IEnumerable{Microsoft.SqlServer.Dac.CodeAnalysis.SqlRuleProblem})~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Cheburashka.Tests.BaselinedRuleTest.LoadTestScripts")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Cheburashka.Tests.BaselinedRuleTest.ListScriptFilenames~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Cheburashka.Tests.RuleTest.CreateModelUsingTestScripts")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:Cheburashka.Tests.RuleTest.DumpErrors(System.Collections.Generic.IList{Microsoft.SqlServer.Dac.Extensibility.ExtensibilityError})")]

