create trigger dbo.CheckOpenTransactionCountCodeRule_DML_Trigger on dbo.Table1
    after insert
as

IF @@TRANCOUNT = 1 ROLLBACK
IF XACT_STATE() = 1 ROLLBACK
IF @@TRANCOUNT = 1 OR XACT_STATE() = 1 ROLLBACK

WHILE @@TRANCOUNT = 1 ROLLBACK
WHILE XACT_STATE() = 1 ROLLBACK
WHILE @@TRANCOUNT = 1 OR XACT_STATE() = 1 ROLLBACK;

RETURN 
