CREATE TABLE dbo.EnforceForeignKeyIsIndexedRule_Table_With_ClusteredIndex (a INT
, CONSTRAINT PK_EnforceForeignKeyIsIndexedRule_Table_With_ClusteredIndex primary KEY (a)
) ;
GO
create table EnforceForeignKeyIsIndexedRule_Table_With_ClusteredIndex_Child (a int
, constraint FK_EnforceForeignKeyIsIndexedRule_Table_With_ClusteredIndex foreign key (a) references EnforceForeignKeyIsIndexedRule_Table_With_ClusteredIndex (a)
)
GO
CREATE UNIQUE CLUSTERED INDEX ix_EnforceForeignKeyIsIndexedRule_Table_With_ClusteredIndex on EnforceForeignKeyIsIndexedRule_Table_With_ClusteredIndex_Child(a)
GO 