--This is valid sql but won't build in the test
--create TABLE dbo.EnforcePrimaryKeyRule_MemoryOptimisedTable_WithOut_PK (a int not NULL
--, b char(10) unique
--)
--WITH (MEMORY_OPTIMIZED = ON, DURABILITY = SCHEMA_ONLY)
--GO
--create table dbo.EnforcePrimaryKeyRule_MemoryOptimisedTable_WithOut_PK_Child (a int not NULL
--, b char(10) unique
--)
--WITH (MEMORY_OPTIMIZED = ON, DURABILITY = SCHEMA_ONLY)
--go
